version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: foodlabel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_labeling_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d food_labeling_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  foodlabel-app:
    build:
      context: .
      target: dev
    container_name: foodlabel-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_REMOTE_DEBUG: "true"
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/food_labeling_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./target/classes:/app/target/classes
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
