spring:
  datasource:
    url: jdbc:postgresql://e2e-db:5432/food_labeling_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
